### ISSUE TITLE
Todo List Tutorial

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/flutter-todo-list-tutorial#14]
The Todo list tutorial could do with some clarification ( I'm *struggling* to follow it as a beginner to Flutter), and could do with going into more detail on *how* things work.

+ [ ] Add setup steps - e.g. *How do I start Simulator?*
+ [ ] Clarify & correct existing tutorial
+ [ ] Add explanations as to *why* things work
+ [ ] Add more screenshots

**Comment by t0mhaines** [comment]
*Whoops*, just seen #13 , which solves quite a few of these problems!

@nelsonic I'm happy to work on this if needed but looks like you've already got someone working on it... Don't want to duplicate our efforts

**Comment by t0mhaines** [comment]
The "layout" section omits a lot of key code, going to try and fix up from scratch using the default docs: https://flutter.dev/docs/development/ui/layout

**Comment by nelsonic** [comment]
Thanks @th0mas ❤️

**Comment by t0mhaines** [comment]
`CustomButton` is not, as far as I can tell, a default Flutter Widget. Might have to start this Todo List from scratch ...

**Comment by nelsonic** [comment]
@th0mas yeah, we _really_ don't need any **`CustomButton`** in this tutorial. 
Please try and use default widgets wherever possible and _document_ when you need to use anything else. 👍
