### ISSUE TITLE
Persisting todo items

### ISSUE THREAD

**Issue by SimonLab** [dwyl/flutter-todo-list-tutorial#18]
The PR https://github.com/dwyl/flutter-todo-list-tutorial/pull/17 focused on explaining how to create a simple UI with the Flutter widgets. However it doesn't explain yet how to persist the items created while the application is running.
We want to describe what are the different way to store/save data and load the information when the application is reopened.

- [x] Simple key-value store system using the [shared_preferences](https://pub.dev/packages/shared_preferences) package. As our data is a bit more complex that just a key-value we will need first to convert the item objects to json and serialised (convert to string) them to be able to save them. #21 
- [ ] Database system with SQLite. see: https://github.com/dwyl/learn-flutter/issues/70
- [ ] API system where we can save the items using a (Phoenix) REST API. We can also see how to use Phoenix Channels with Flutter, this can be useful when creating collaborative todo list for example. Dependent on: https://github.com/dwyl/phoenix-todo-list-tutorial/issues/53

see also https://flutter.dev/docs/cookbook/persistence

**Comment by nelsonic** [comment]
@SimonLab how long would it take to upgrade https://github.com/dwyl/phoenix-todo-list-tutorial to have a _basic_ API that would allow Flutter to GET/POST to use it as a Backend? 💭

**Comment by SimonLab** [comment]
@nelsonic I don't think it should take too long to add and it can be nice to see the API used with Flutter

**Comment by nelsonic** [comment]
Please See: https://github.com/dwyl/phoenix-todo-list-tutorial/issues/53

**Comment by nelsonic** [comment]
@SimonLab can we consider this done? 💭 
This tutorial is using `riverpod`: 
https://github.com/dwyl/flutter-todo-list-tutorial/blob/575a8bacdd62a91ef8eba7ec3c0e97faf37d43af/pubspec.yaml#L41
