### ISSUE TITLE
Why? What? Who? How?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/flutter-todo-list-tutorial#2]
## Why? 

We need a way of helping people **learn `Flutter`** the **_right_ way** as **_fast_** as **possible**.
The "right way" to build _anything_ is to follow best practices for both architecture and reliability. 
If you are **`new`** to a particular language/framework simply _search_ for them:
e.g: [google.com/search?q=**flutter**+**best**+**practices**](https://www.google.com/search?q=flutter+best+practices)
For which the _many_ relevant results: (_we should summarise these **`before`**  building the Todo List_)
+ Official best practices: https://flutter.dev/docs/perf/rendering/best-practices
+ Gavin Doughtie - Architecting the Reactive Flutter App: http://youtu.be/n_5JULTrstU [28:43]
+ Keep it Simple, State: Architecture for Flutter Apps: https://youtu.be/zKXz3pUkw9A [28:59]
+ Effective code in your Flutter app from the beginning: https://medium.com/flutter-community/effective-code-in-your-flutter-app-from-the-beginning-e597444e1273

> We know from our experience of building software that Apps without _tests_ fall apart very quickly.
(_if you are totally **`new`** to **software engineering** in a **team**, you can be excused for not knowing that **TDD** is **essential** to the success of Apps built by multiple people ..._)
That's why we wrote the [github.com/dwyl/**learn-tdd**](https://github.com/dwyl/learn-tdd) tutorial. So it's _easy_ for _everyone_ to learn.
We wrote the [github.com/dwyl/**javascript**-**todo**-**list**-**tutorial**](https://github.com/dwyl/javascript-todo-list-tutorial) to help people _practice_ TDD while building a real-world App. Now there's _really no excuse_ not to follow TDD.

There are _already **several**_ good examples of Flutter apps: https://github.com/dwyl/learn-flutter/issues/19
If we simply _copy_ one of those Todo List examples without adding any instructions or following best practices we will have _failed_ to add any _value_. There's no point 
What does _not_ yet exist is a tutorial that builds an app from scratch following ***best practices*** with a full test suite and ***documentation*** of all the steps and functions.

Compare and contrast the following two Phoenix Chat examples:
**a**. https://github.com/chrismccord/phoenix_chat_example (_the "official" example_)
**b**. https://github.com/dwyl/phoenix-chat-example (_the @dwyl step-by-step example/tutorial_)
Which one would you rather learn from as a _complete_ beginner? 
> **Note**: this is not meant as a "criticism" of Chris, he is very busy making other [awesome things](https://github.com/phoenixframework/phoenix_live_view).
> It's just to point out that there is a _huge_ gap between a _basic_ example and a _comprehensive_ one.

## What?

A step-by-step example/tutorial showing people how to build a Todo List App in Flutter 
following the best practices: 
+ "**_Documentation_ Driven Development**" https://opensource.com/article/17/8/doc-driven-development
+ "**_Test_ Driven Development**" 
+ Whichever **architecture** is most **maintainable** one. (_suggestions as comments below_)

## Who?

Anyone @dwyl who wants to learn Flutter can _contribute_ to the example/tutorial provided they understand that we want it to represent the _best_ possible Flutter example _possible_. 

We are writing the example for anyone `else` in the wider development community who wants to learn Flutter and build their own app(s). 

## How?

This is a good _starting_ point for code inspiration:
https://github.com/brianegan/flutter_architecture_samples/tree/master/redux
But we want to write a _comprehensive_ step-by-step guide. 

# Todo: Build a TodoMVC Clone in Flutter

This is what we need to do for this repository to be considered "done":

+ [x] Read and _follow_ all steps in the JavaScript Todo List Tutorial: [dwyl/**javascript**-todo-list-tutorial](https://github.com/dwyl/javascript-todo-list-tutorial)
  > Only by _fully_ understanding the flow of Test Driven Development (TDD) can we build a tutorial that follows best practices. 
+ [x] Read, understand and _summarise_ how to do TDD in Dart/Flutter: #1
+ [x] Ensure that the "setup" instructions in [github.com/dwyl/**learn-flutter**](https://github.com/dwyl/learn-flutter) are _complete_ including a "trouble-shooting" section for people who get stuck. We don't want people stumbling at the [first hurdle](https://idioms.thefreedictionary.com/fall+at+the+first+hurdle)
+ [ ] Build a Todo List Application that implements _all_ of the features described in the TodoMVC specification. see: https://github.com/dwyl/javascript-todo-list-tutorial#requirements
+ [ ] Split the tutorial into as many sections (_markdown files_) as needed and 
  + [ ] include "**previous**" and "**next**" links at the bottom of each file.

**Comment by miguelmartins17** [comment]
@nelsonic I'm sorry. I thought I was doing it the right way.
I'll try to help you get better. Do you want me to change the answers to the questions by the answers you just added?

**Comment by nelsonic** [comment]
@miguelmartins17 please never apologise when it's _my_ fault for not making it clear. 👍 
You are already making a _good_ start on this. 🥇 
We need our tutorials to be the _best_ they can be and we don't ever want to be the cause of "bad habits" in people who are learning. That's why we have to be _extra_ proactive in reading about the "best practices" ***`before`*** we write something. Remember the _best_ teacher you ever had and compare them to the _worst_ one you had or heard of. Aspire to be the _best_ teacher, it will _automatically_ make you the _best_ at the subject matter. Always think about the person _struggling_ to learn the subject, you don't want them to _ever_ have a reason to "give up" learning.

**Comment by miguelmartins17** [comment]
I'm gonna take some time to read how the TDD works.

https://github.com/dwyl/learn-tdd

**Comment by miguelmartins17** [comment]
I'm working on summarizing what's here: 
https://flutter.dev/docs/perf/rendering/best-practices

 I'll start work on Flutter's repository.
Will we include the information in this document in the Tutorial repository or the Flutter repository ? 💭

**Comment by miguelmartins17** [comment]
@nelsonic Where should we put Flutter information in the Flutter repository or the Flutter Tutorial ? 🤔

**Comment by nelsonic** [comment]
Miguel what "Flutter information" are you referring to?

**Comment by miguelmartins17** [comment]
I'm talking about the summary of the best practices of Flutter

**Comment by nelsonic** [comment]
`learn-flutter`

**Comment by nelsonic** [comment]
If it's a _generic_ principal or practice, it goes in the _generic_ repository. 
That is the pattern we have followed in _all_ our tutorials.

**Comment by miguelmartins17** [comment]
Of course then the information regarding these four documents goes to the _**learn-flutter**_.





![Screen Shot 2020-02-06 at 17 44 40](https://user-images.githubusercontent.com/27420533/73963618-92390d80-4908-11ea-8f6c-b479a55ec377.png)

**Comment by miguelmartins17** [comment]
What do you think of this example of the use of TDD in Flutter ? 💭  

https://medium.com/learnfazz/common-mistakes-in-tdd-and-tdd-in-flutter-2bf682071036

**Comment by nelsonic** [comment]
@miguelmartins17 thanks for sharing the link. 🔗 
Please in future, _summarise_ what you _learned_ from reading an article to save others the time.
You could have saved me at _least_ an hour by _trying_ to follow the instructions in the link you shared.

While I _applaud_ the author  @adalberht for _writing_ the article, (_practice is the only way to get better_)
I _really_ wish they had user a _free_ grammar checker. It makes it _really_ difficult to read when my brain has to stop correcting grammar and focus on the _intent_ ... 🙄 

I ran the article through https://www.grammarly.com (_**free** online writing checker_) and it wasn't pretty:
![image](https://user-images.githubusercontent.com/194400/74094010-3ae69900-4ad2-11ea-895e-419509b9923b.png)

(_this is why **all learning content** should be **editable** so that it can be **improved**... 
or perhaps Medium should include grammar checking in their blogging platform...?_)

The "Red, Green, Refactor" cycle is good. (_looks familiar_ ... https://github.com/dwyl/learn-tdd#how ...)
The post is _mega_ incomplete which _super_ frustrating!
I actually tried to _follow_ the post: 
https://github.com/dwyl/learn-flutter/blob/flutter-tdd-issue%2315/test/image_picker_bottom_sheet_test.dart 

I spent _hours_ trying to make's tutorial work but the code simply does not render!
I _commented_ on the post:
![image](https://user-images.githubusercontent.com/194400/74093878-230e1580-4ad0-11ea-8a31-5724b9faad38.png)
The author seems talented and conscientious, but the Gists and non-functioning code is a major letdown. 

I **_really_ hate it** when people share "gists" of code instead of linking to the _full_ working example!
There is no extra _effort_ to put the code on **GitHub** instead of **Gist** and it makes the life the person _reading_ the post _infinitely_ easier because they can simply **`git clone`** the code and _run_ it!

Along the way I read: 
https://medium.com/flutterpub/writing-and-running-widget-tests-from-android-studio-d63b9fea21c5
Which lead me to:
https://flutter.dev/docs/cookbook/testing/integration/introduction
I was able to run the example in the official cookbook:
![image](https://user-images.githubusercontent.com/194400/74093970-9cf2ce80-4ad1-11ea-827b-0f4153b09464.png)
I suggest you try and follow it.

Also, how much of the links Simon shared in #1 have you followed?

<hr />

### Addendum: 

The author of the post _thanked_ me for my feedback:
![image](https://user-images.githubusercontent.com/194400/74102182-00641700-4b39-11ea-80e6-8c41c2ab03a6.png)
![image](https://user-images.githubusercontent.com/194400/74102194-1d98e580-4b39-11ea-9baf-c5a9f4f67dfe.png)
The outcome is that _other_ people will not suffer the same frustration in future 
and the author can improve their posts with more extensive/helpful examples.
